### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by R3tr0BoiDX** [R3tr0BoiDX/tasbot_eyes#8]
There's a teeny tiny memory leak. No idea where.

**Comment by R3tr0BoiDX** [comment]
valgrind reports `27,268 (24 direct, 27,244 indirect) bytes in 1 blocks are definitely lost in loss record 16 of 16` for `gif.c:readAnimation()` when `animation = malloc(sizeof(Animation));` is called. See [here](https://github.com/R3tr0BoiDX/tasbot_eyes/blob/a90cdea505efd0a2c51285b55b1d1963bc03b28e/gif.c#L57).

However, `tasbot.c:freeAnimation()` should free all of the animation structure? See [here](https://github.com/R3tr0BoiDX/tasbot_eyes/blob/a90cdea505efd0a2c51285b55b1d1963bc03b28e/tasbot.c#L274).

@compucat, if you eventually have a sec, can I maybe please get you to look at that?

**Comment by Inverted** [comment]
Can't seem to replicate this specific Valgrind leak. I don't have a Pi with an LED board connected, but I assume this would still happen without that.  Could you provide more details on how to replicate it?

**Comment by R3tr0BoiDX** [comment]
In fairness, I must also confess, I got that report from valgrind when I tested it on my PC. Might be a wise idea to maybe also let run valgrind on the actual Pi eventually. Anyway, I used the valgrind integration of CLion and let the program run for a while, maybe 15 min? I cant quite recall. Ill try to reproduce it myself and let you know (and also, what valgrind reports when I run it on the actual Pi).

**Comment by Inverted** [comment]
How do you have the program exit cleanly when it's running the loop? Valgrind gives false positives when I force-close it with Ctrl+C. Modifying the main loop to only run an x amount of times only gives a warning about the thread started in `network.c`, which makes sense given that it's blocking & reading a socket so it can't cleanly exit.

**Comment by R3tr0BoiDX** [comment]
Oii, that could explain it then, why you arent able to reproduce it then. I just stop running the program within CLion and iirc that just sends an SIGINT to the program. Ill look into it tomorrow! Thx for the heads up, I was unaware of that fact!

**Comment by R3tr0BoiDX** [comment]
Hey, sorry @Inverted for the delay, there was some uni stuff I needed to get done. I tried running the program with valgrind memcheck on the Pi now, however, I have a slight issue. The eye software needs superuser privileges to run, else its not able to communicate with the LEDs. Err, how do I do that?

I tried (sudo on `valgrind`)
```
sudo valgrind --tool=memcheck --xml=yes --xml-file=./tasbot-memcheck.xml  --gen-suppressions=all --leak-check=full --leak-resolution=high --track-origins=yes --vgdb=no ./tasbot_eyes -X -d 18 -c -s 2 
```
as well as (sudo on `./tasbot_eyes`)
```
valgrind --tool=memcheck --xml=yes --xml-file=./tasbot-memcheck.xml  --gen-suppressions=all --leak-check=full --leak-resolution=high --track-origins=yes --vgdb=no sudo ./tasbot_eyes -X -d 18 -c -s 2 
```
both with no success.

I also tried to login as superuser with `sudo su` and then run (no sudo at all)
```
valgrind --tool=memcheck --xml=yes --xml-file=./tasbot-memcheck.xml  --gen-suppressions=all --leak-check=full --leak-resolution=high --track-origins=yes --vgdb=no ./tasbot_eyes -X -d 18 -c -s 2
```
which also failed. (Either it can't handle system call 407 or we missing permission)

**Comment by Inverted** [comment]
Hmm I'm not sure why none of those worked. Valgrind should just work on a Pi, and running it as superuser should have all the permissions you would ever need I'd assume. Do you get any specific error messages/behaviour?

**Comment by R3tr0BoiDX** [comment]
software was now running for 48+ hours. within the first 24 hours it grew from 4 mb to 11 mb. another 24 hours later it had the exact same memory usage. i  ont understand what caused it to inflate, but as it is now, I frankly dont care
